detail/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'detail'

urlpatterns = [
    path('admin/', admin.site.urls),
    path("<int:detail_id>", views.detailproduk, name='detailproduk'),
    # path("testijson", views.testijson, name='testijson')
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    # dilanjutkan ...
]

keranjang/urls.py
from django.urls import path
from . import views

app_name = 'keranjang'

urlpatterns = [
    path('', views.keranjang, name='keranjang'),
    path('checkout', views.checkout, name='checkout'),
    path('add/<int:detail_id>', views.addToKeranjang, name='tambah'),
    path('addPOST', views.addPOST, name='addPOST'),
    path('delPOST', views.delPOST, name='delPOST'),
    path('incPOST', views.incPOST, name='incPOST'),
    path('decPOST', views.decPOST, name='decPOST'),
]

produk/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views
# from .views import ajax_posting, addpro

app_name = 'produk'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.listproduk, name='listproduk'),
    path("addproduk/", views.addproduk, name='addproduk'),
    # path('postajax', views.ajax_posting, name='ajax'),# ajax-posting / name = that we will use in ajax url
    # path("detailproduct/<int:detail_id>", views.detailproduk, name='detailproduk')
]
#landing pagenya ke list produk, ngambl dr models yg ada di list produk buat detail sm testi

tkppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('listproduk/', include('produk.urls')),
    path('keranjang/', include('keranjang.urls')),
    path('bantuan/', include('bantuan.urls')),
    path('detail/', include('detail.urls')),
    path('account/', include('login.urls')),
    #path('login/', LoginView.as_view(template_name='login.html'), name="login"),
    #path('logout/', LogoutView.as_view(template_name='logout.html'), name="logout"),
]

handler404 = views.handler404
handler500 = views.handler500

produk/models.py
from django.db import models

# Create your models here.
class AddProduk(models.Model):
    nama = models.CharField(max_length=50, blank = False)
    # foto = models.ImageField(upload_to='static/img/',  default='img/logo.png')
    foto = models.TextField(default='https://mmc.tirto.id/image/otf/500x0/2019/10/18/pppk_ratio-16x9.jpg')
    # harga = models.CharField(max_length=300)
    harga = models.PositiveIntegerField()
    stok = models.IntegerField(default='1')
    penjual = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    deskripsi = models.TextField()

    def __str__(self):
        return self.nama

produk/forms.py
from django import forms
from .models import AddProduk

class FromAdd(forms.Form) :
    penjual = forms.CharField(
        label = '',
        widget=forms.TextInput(attrs={
        # 'cols' : '10',
        # 'rows' : '20',
        'class' : 'form-control',
        'id' : 'penjual',
        'placeholder' : 'Nama Penjual/Perusahaan',
        'type' : 'text',
        'required' : True, 
        'style': 'padding: 5%; margin-top: 5%; margin-bottom: 10%; font-size: 16px;'
    }))

    email = forms.EmailField(
        label = '',
        widget=forms.EmailInput(attrs={
        'class' : 'form-control',
        'id' : 'email',
        'placeholder' : 'Email',
        'type' : 'text',
        'required' : True,
        'style': 'padding: 5%; margin-top: 5%; margin-bottom: 10%; font-size: 16px;'
        
    }))

    nama = forms.CharField(
        label ='',
        widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'id' : 'nama',
        'placeholder' : 'Nama Barang',
        'type' : 'text',
        'required' : True,
        'style': 'padding: 5%; margin-top: 5%; margin-bottom: 10%; font-size: 16px;'
    }))

    harga = forms.IntegerField(
        label = '',
        widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'id' : 'harga',
        'placeholder' : 'Harga Barang (contoh : 50000)',
        'type' : 'text',
        'required' : True,
        'style': 'padding: 5%; margin-top: 5%; margin-bottom: 10%; font-size: 16px;'
    }))

    stok = forms.IntegerField(
        label = '',
        widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'id' : 'stok',
        'placeholder' : 'Stok Barang',
        'type' : 'text',
        'required' : True,
        'style': 'padding: 5%; margin-top: 5%; margin-bottom: 10%; font-size: 16px;'
    }))

    deskripsi = forms.CharField(
        label = '',
        widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'id' : 'deskripsi',
        'placeholder' : 'Deskripsi Barang',
        'type' : 'text',
        'required' : True,
        'style': 'padding: 5%; margin-top: 5%; margin-bottom: 10%; font-size: 16px;'
    }))

    foto = forms.CharField(
        label = '',
        widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'id' : 'foto',
        'placeholder' : 'Masukkan link Foto Barang',
        'type' : 'text',
        'required' : True,
        'style': 'padding: 5%; margin-top: 5%; margin-bottom: 5%; font-size: 16px;'
    }))

produk/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from .forms import FromAdd
from .models import AddProduk
import json

# Create your views here.
def listproduk(request):
    if request.method =="POST" and request.POST.get("carinama") !=None:
        search = request.POST.get("carinama")
        produk = AddProduk.objects.filter(nama__contains=search)
        response = {
            'produk' : produk,
        }
        return render(request,'listproduk.html', response)
    else:
        produk = AddProduk.objects.all()
        response = {
            'produk' : produk,
        }
        return render(request,'listproduk.html', response)

    # except:
        # return redirect('/listproduk/addproduct')

def addproduk(request) : 
    responses = {}
    if request.method == 'GET':
        form = FromAdd()
        responses['form'] = form
        return render(request, 'addproduk.html', responses)
        
    else:
        if request.is_ajax():
            if request.user.is_authenticated:
                form = FromAdd(request.POST)
                if form.is_valid():
                    produk = AddProduk()
                    produk.penjual = form.cleaned_data['penjual']
                    produk.email = form.cleaned_data['email']
                    produk.nama = form.cleaned_data['nama']
                    produk.harga = form.cleaned_data['harga']
                    produk.stok = form.cleaned_data['stok']
                    produk.deskripsi = form.cleaned_data['deskripsi']
                    produk.foto = form.cleaned_data['foto']
                    produk.save()
                    return JsonResponse({'success': True})
        return JsonResponse({'success': False})
        # return redirect ("/listproduk/")
        return render(request, "addproduk.html", {"form" : form})

produk/templates/addproduk.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Tambah Produk {% endblock %}

{% block content %}

<div class="d-flex flex-row-reverse" style="display: flex;">
{% comment %} Click me! {% endcomment %}
  <button id="coklatbt" style="background-color: #E0C387; margin: 10px; padding: 20px;"></button>
  <button id="dongkerbt" style="background-color: #00395E; margin: 10px; padding: 20px;"></button>
  <button id="birubt" style="background-color: #CEE8F9; margin: 10px; padding: 20px;"></button>
</div>

   <div class="container " style="margin-top:5%;text-align:center">
{% if user.is_authenticated %}
    <h1>Tambah Produk</h1>
    <div class="row d-flex justify-content-center">
         <div id="cardadd" class="card " style="width:35rem; background:#E0C387">
            <div class="col-md-12 justify-content-center">
               <div class="myform form ">
                  <form id="formpd" action="" method="POST" >
                     {% csrf_token %}
                     <div class="form-group" style=" padding-right:5%; padding-left:5%; padding-top: 5%">
                        {{ form }}
                        <div class="text-center" >
                           <input id="submit" type="submit" class="btn btn-light flex-row-reverse" value="submit">
                        </div>
                     </div>
                  </form>
               </div>
            </div>
               <div id="output"> </div>
         </div>
      </div>
{% else %}
  <div class="container text-center my-5">
    <div class="row">
      <div class="col">
        <h2>Anda harus memiliki akun untuk menambahkan produk</h2>
        <div class="d-flex justify-content-center my-5">
          <a class="btn btn-lg btn-dark button2 mx-5" href="{% url 'login' %}">Masuk</a>
          <a class="btn btn-lg btn-dark button2 mx-5" href="{% url 'signup' %}">Mendaftar</a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</div>

{% comment %} <div id="output">  </div> 
<h1> test </h1>
</div>  {% endcomment %}

<script>
var url2 = '{% url "produk:addproduk" %}'
</script>
<script src="{% static 'js/produk.js' %}"></script>

{% endblock  %}

produk/templates/listproduk.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}List Produk {% endblock %}

{% block content %}

    <!-- Back to top button -->
    <a id="buttonproduk"></a>

    <div style="margin-top:3%; margin-left:3%">
        <div class="row" style="" id="rowproduk">
            {% for pd in produk %}
               {% if pd.stok > 0 %}
                <div id="listpd" class="shadow card" style="text-align: left; width: 18rem; margin-left:4%; margin-bottom:4%; max-width: 240px;">
                    <img src="{{ pd.foto }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 id="nama" class="card-title">{{ pd.nama }}</h5>
                                <a href="{% url 'detail:detailproduk' detail_id=pd.id %}"> 
                                    <button  style='background-color:#00395E; border: #00395E; width:94px; height:31px;' id="detailbt" class="btn btn-primary btn-lgN">Details</button>
                                </a>
                                <a href="{% url 'keranjang:tambah' detail_id=pd.id %}"> 
                                    <img src={% static 'troli.png' %} >
                                </a>
                            <h5 style="text-align:right">Rp{{ pd.harga|intcomma }}</h5>
                        </div>
                    </div>
                {% endif %}    
            {% endfor %}
        </div>
    </div>


<script src="{% static 'js/produk.js' %}"></script>

{% endblock content%}