home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    # dilanjutkan ...
]

keranjang/urls.py
from django.urls import path
from . import views

app_name = 'keranjang'

urlpatterns = [
    path('', views.keranjang, name='keranjang'),
    path('checkout', views.checkout, name='checkout'),
    path('add/<int:detail_id>', views.addToKeranjang, name='tambah'),
    path('addPOST', views.addPOST, name='addPOST'),
    path('delPOST', views.delPOST, name='delPOST'),
    path('incPOST', views.incPOST, name='incPOST'),
    path('decPOST', views.decPOST, name='decPOST'),
]

produk/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views
# from .views import ajax_posting, addpro

app_name = 'produk'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.listproduk, name='listproduk'),
    path("addproduk/", views.addproduk, name='addproduk'),
    # path('postajax', views.ajax_posting, name='ajax'),# ajax-posting / name = that we will use in ajax url
    # path("detailproduct/<int:detail_id>", views.detailproduk, name='detailproduk')
]
#landing pagenya ke list produk, ngambl dr models yg ada di list produk buat detail sm testi

tkppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('listproduk/', include('produk.urls')),
    path('keranjang/', include('keranjang.urls')),
    path('bantuan/', include('bantuan.urls')),
    path('detail/', include('detail.urls')),
    path('account/', include('login.urls')),
    #path('login/', LoginView.as_view(template_name='login.html'), name="login"),
    #path('logout/', LogoutView.as_view(template_name='logout.html'), name="logout"),
]

handler404 = views.handler404
handler500 = views.handler500

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
    <script src="{% static 'js/scripts.js' %}"></script>
    <title>{% block title %}MEDISALE{% endblock %}</title>
    <!--Fontawesome 5-->
    <script src="https://kit.fontawesome.com/8a455c0870.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {% block meta %}
    {% endblock meta %}
</head>

<body>
    <nav class="sticky-top shadow">
        <nav class="navbar navbar-expand-lg sticky-top navbar-light" style="background-color: white;">
            <a class="navbar-brand" href="/">
                <img src="{% static 'img/logo.png' %}" alt="Logo" height="40px" class="d-inline-block align-top">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav" style="text-decoration: navy;">
                    <li class="nav-item">
                        <a class="nav-link" href="/"><b>BERANDA</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'produk:listproduk' %}"><b>PRODUK</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'keranjang:keranjang' %}"><b>KERANJANG</b></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/bantuan"><b>BANTUAN</b></a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a class="nav-link" href="/account/"><b>AKUN</b></a>
                    </li>
                    {% else %}
                    <li>
                        <a class="nav-link btn btn-sm mx-1 shadow" style="color: white !important; background-color: #00395e; border: white;" href="{% url 'login' %}"><b>LOGIN</b></a>
                    </li>
                    <li>
                        <a class="nav-link btn btn-sm mx-1 shadow" style="color: white !important; background-color: #00395e; border: white;" href="{% url 'signup' %}"><b>SIGN UP</b></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% if hide_nav_2 == None %}
            {% include 'navbar2.html' %}
        {% endif %}
    </nav>
    <div style="min-height: 90vh;">
        {% block content %}{% endblock %}
    </div>
    {% if hide_footer == None %}
        {% include 'footer.html' %}
    {% endif %}
</body>
</html>

templates/footer.html
<footer class="footer">
    <p>Made with 💜 by Kelompok D07 PPW</p>
</footer>

templates/navbar2.html
<nav class="navbar navbar-dark sticky-top justify-content-between" style="background-color: #00395e;">
    <form class="form-inline" action="{% url 'produk:listproduk' %}" method="POST">
        {% csrf_token %}
        <input type="text" class="form-control" name="carinama" placeholder="Cari Produk" aria-label="Cari Produk">
        <button class="btn btn-outline-primary" type="submit" style="background-color:#CEE8F9;">Search</button>
    </form>
    <a href="{% url 'produk:addproduk'%}"> 
        <button type="button" class="btn btn-light flex-row-reverse"><b>TAMBAH PRODUK</b></button>
    </a>
</nav>